import { assets } from "./assets.js";

export const mattressCategories = [
  "All Mattresses",
  "Pocket Spring",
  "Memory Foam",
  "Latex",
  "Gel Memory Foam",
  "Bonnell Spring",
  "Ortho Support",
];

function size(name, dimensions, price) {
  return { id: dimensions.replace(/\s/g, ""), name, dimensions, price };
}

export const products = [
  {
    slug: "prince",
    name: "Prince",
    type: "Pocket Spring",
    badge: "BESTSELLER",
    badgeColor: "red",
    image: assets.products.prince,
    layersImage: assets.products.layers.prince,
    thickness: "10 Inches",
    warranty: "10 Years Warranty",
    usage: "Euro Top",
    specs: "10 Inches | Gel Memory Foam | Zero Suspension Pocket Spring | Euro Top",
    shortSpecs: "10 Inches | Gel Memory Foam | Pocket Spring",
    price: 59400,
    tagline: "Gel comfort with zero-suspension pocket support.",
    description:
      "A 10-inch Euro Top mattress combining Gel Memory Foam with Zero Suspension Pocket Spring support for balanced comfort and reduced partner disturbance.",
    highlights: [
      "10 inches thickness",
      "Gel Memory Foam with Zero Suspension Pocket Spring",
      "Euro Top finish",
      "10 Years Warranty",
    ],
    layers: [
      "Euro Top quilted surface",
      "Gel Memory Foam",
      "Zero Suspension Pocket Spring",
      "Support base",
    ],
    rating: 4.8,
    reviews: 320,
    sizes: [size("King", "180 × 200 cm", 59400)],
  },
  {
    slug: "king",
    name: "King",
    type: "Pocket Spring",
    badge: null,
    image: assets.products.king,
    layersImage: assets.products.layers.king,
    thickness: "12 Inches",
    warranty: "10 Years Warranty",
    usage: "Euro Top",
    specs: "12 Inches | Memory Foam | Pocket Spring | High Density Foam | Euro Top",
    shortSpecs: "12 Inches | Memory Foam | Pocket Spring",
    price: 66000,
    tagline: "Royal comfort with layered spring support.",
    description:
      "A 12-inch Euro Top mattress built with Memory Foam, Pocket Spring and High Density Foam for resilient, supportive comfort.",
    highlights: [
      "12 inches thickness",
      "Memory Foam with Pocket Spring and High Density Foam",
      "Euro Top finish",
      "10 Years Warranty",
    ],
    layers: [
      "Euro Top quilted surface",
      "Memory Foam",
      "Pocket Spring unit",
      "High Density Foam",
    ],
    rating: 4.7,
    reviews: 185,
    sizes: [size("King", "180 × 200 cm", 66000)],
  },
  {
    slug: "brittany",
    name: "Brittany",
    type: "Latex",
    badge: "NEW",
    badgeColor: "green",
    image: assets.products.brittany,
    layersImage: assets.products.layers.brittany,
    thickness: "8 Inches",
    warranty: "10 Years Warranty",
    usage: "Single Side Usage",
    fabric: "Tencel Fabric",
    specs: "8 Inches | Latex | Gel Memory Foam | Tencel Fabric | Single Side",
    shortSpecs: "8 Inches | Latex & Gel Memory Foam",
    price: 63000,
    tagline: "Responsive latex with cool gel comfort.",
    description:
      "An 8-inch mattress combining Latex and Gel Memory Foam with Tencel Fabric. Designed for single-side usage and backed by a 10-year warranty.",
    highlights: [
      "8 inches thickness",
      "Latex and Gel Memory Foam",
      "Tencel Fabric",
      "Single Side Usage",
      "10 Years Warranty",
    ],
    layers: ["Tencel Fabric", "Latex", "Gel Memory Foam", "Support core"],
    rating: 4.6,
    reviews: 142,
    sizes: [size("King", "180 × 200 cm", 63000)],
  },
  {
    slug: "celeste",
    name: "Celeste",
    type: "Memory Foam",
    badge: "POPULAR",
    badgeColor: "blue",
    image: assets.products.celeste,
    layersImage: assets.products.layers.celeste,
    thickness: "8 Inches",
    warranty: "10 Years Warranty",
    usage: "Single Side Usage",
    fabric: "Tencel Fabric",
    specs: "8 Inches | Charcoal Memory Foam | Tencel Fabric | Single Side",
    shortSpecs: "8 Inches | Charcoal Memory Foam",
    price: 28800,
    tagline: "Charcoal-infused comfort for cooler sleep.",
    description:
      "An 8-inch Charcoal Memory Foam mattress with Tencel Fabric, designed for single-side usage and backed by a 10-year warranty.",
    highlights: [
      "8 inches thickness",
      "Charcoal Memory Foam",
      "Tencel Fabric",
      "Single Side Usage",
      "10 Years Warranty",
    ],
    layers: ["Tencel Fabric", "Charcoal Memory Foam", "Support foam"],
    rating: 4.8,
    reviews: 256,
    sizes: [
      size("King", "180 × 200 cm", 55500),
      size("King", "180 × 190 cm", 55500),
      size("Queen", "150 × 200 cm", 48000),
      size("Queen", "150 × 190 cm", 48000),
      size("Single", "90 × 200 cm", 28800),
    ],
  },
  {
    slug: "prada",
    name: "Prada",
    type: "Gel Memory Foam",
    badge: null,
    image: assets.products.prada,
    layersImage: assets.products.layers.prada,
    thickness: "8 Inches",
    warranty: "10 Years Warranty",
    usage: "Double Side Usage",
    specs: "8 Inches | Gel Memory Foam | Special Cutting | Convoluted Foam | Double Side",
    shortSpecs: "8 Inches | Gel Memory Foam",
    price: 45000,
    tagline: "Layered gel comfort with double-sided use.",
    description:
      "An 8-inch mattress using Gel Memory Foam with Special Cutting and Convoluted Foam. Designed for double-side usage and backed by a 10-year warranty.",
    highlights: [
      "8 inches thickness",
      "Gel Memory Foam with Special Cutting and Convoluted Foam",
      "Double Side Usage",
      "10 Years Warranty",
    ],
    layers: ["Gel Memory Foam", "Special cutting foam", "Convoluted Foam", "Support core"],
    rating: 4.9,
    reviews: 98,
    sizes: [
      size("King", "180 × 200 cm", 51000),
      size("King", "180 × 190 cm", 51000),
      size("Queen", "150 × 200 cm", 45000),
      size("Queen", "150 × 190 cm", 45000),
    ],
  },
  {
    slug: "lilly",
    name: "Lilly",
    type: "Pocket Spring",
    badge: null,
    image: assets.products.lilly,
    layersImage: assets.products.layers.lilly,
    thickness: "10 Inches",
    warranty: "10 Years Warranty",
    usage: "Pillow Top",
    specs: "10 Inches | Memory Foam | High Density Foam | Pillow Top | 5 Zoned Pocket Spring",
    shortSpecs: "10 Inches | 5 Zoned Pocket Spring",
    price: 43500,
    tagline: "Zoned pocket support with a plush pillow top.",
    description:
      "A 10-inch pillow-top mattress with Memory Foam, High Density Foam and a 5 Zoned Pocket Spring unit for targeted support across the body.",
    highlights: [
      "10 inches thickness",
      "Memory Foam and High Density Foam with Pillow Top",
      "5 Zoned Pocket Spring",
      "10 Years Warranty",
    ],
    layers: [
      "Knit Fabric",
      "Comfort Fiber",
      "Memory Foam",
      "Non-woven Fabric",
      "High Density Foam",
      "Convoluted Foam",
      "Isolated Pad",
      "5 Zoned Pocket Spring Unit with Iron Frame",
    ],
    rating: 4.7,
    reviews: 88,
    sizes: [
      size("King", "180 × 200 cm", 49500),
      size("Queen", "150 × 200 cm", 43500),
      size("Queen", "150 × 190 cm", 43500),
    ],
  },
  {
    slug: "magna",
    name: "Magna",
    type: "Ortho Support",
    badge: null,
    image: assets.products.magna,
    layersImage: assets.products.layers.magna,
    thickness: "8 Inches",
    warranty: "10 Years Warranty",
    usage: "Double Side Usage",
    fabric: "Bamboo Fabric",
    specs: "8 Inches | High Density PU Foam | Bamboo Fabric | Double Side",
    shortSpecs: "8 Inches | High Density PU Foam",
    price: 39000,
    tagline: "Firm, breathable support for everyday sleep.",
    description:
      "An 8-inch High Density PU Foam mattress with Bamboo Fabric, Medium Density Foam and double-side usage for dependable support.",
    highlights: [
      "8 inches thickness",
      "High Density PU Foam with Medium Density Foam",
      "Bamboo Fabric with inner cover",
      "Double Side Usage",
      "10 Years Warranty",
    ],
    layers: [
      "Bamboo Fabric",
      "Inner Cover",
      "Medium Density Foam",
      "High Density Foam",
      "Medium Density Foam",
      "Inner Cover",
      "Bamboo Fabric",
    ],
    rating: 4.5,
    reviews: 104,
    sizes: [
      size("King", "180 × 200 cm", 45600),
      size("Queen", "150 × 200 cm", 39000),
      size("Queen", "150 × 190 cm", 39000),
    ],
  },
  {
    slug: "elita",
    name: "Elita",
    type: "Bonnell Spring",
    badge: null,
    image: assets.products.elita,
    layersImage: assets.products.layers.elita,
    thickness: "8 Inches",
    warranty: "10 Years Warranty",
    usage: "Pillow Top",
    specs: "8 Inches | High Density Foam | Pillow Top | Bonnell Spring",
    shortSpecs: "8 Inches | High Density Foam | Bonnell Spring",
    price: 30900,
    tagline: "Pillow-top comfort with Bonnell Spring support.",
    description:
      "An 8-inch High Density Foam pillow-top mattress with Bonnell Spring support and a 10-year warranty.",
    highlights: [
      "8 inches thickness",
      "High Density Foam with Pillow Top",
      "Bonnell Spring mattress",
      "10 Years Warranty",
    ],
    layers: ["Pillow Top", "High Density Foam", "Bonnell Spring unit", "Support base"],
    rating: 4.7,
    reviews: 116,
    sizes: [
      size("King", "180 × 200 cm", 37050),
      size("King", "180 × 190 cm", 37050),
      size("Queen", "150 × 190 cm", 30900),
    ],
  },
  {
    slug: "belle",
    name: "Belle",
    type: "Ortho Support",
    badge: null,
    image: assets.products.belle,
    layersImage: assets.products.layers.belle,
    thickness: "6 Inches",
    warranty: "10 Years Warranty",
    usage: "Single Side Usage",
    specs: "6 Inches | High Density PU Foam | Single Side",
    shortSpecs: "6 Inches | High Density PU Foam",
    price: 13950,
    tagline: "Reliable support in a practical profile.",
    description:
      "A 6-inch High Density PU Foam mattress with single-side usage and a 10-year warranty.",
    highlights: [
      "6 inches thickness",
      "High Density PU Foam",
      "Single Side Usage",
      "10 Years Warranty",
    ],
    layers: ["Quilted surface", "High Density PU Foam", "Support base"],
    rating: 4.6,
    reviews: 72,
    sizes: [
      size("King", "180 × 200 cm", 22200),
      size("King", "180 × 190 cm", 22200),
      size("Queen", "150 × 200 cm", 18750),
      size("Queen", "150 × 190 cm", 18750),
      size("Double", "120 × 190 cm", 17250),
      size("Single", "90 × 190 cm", 13950),
    ],
  },
];

/** Display order on /mattresses “All” grid (matches matters.png 4×2). */
export const mattressCollectionOrder = [
  "prince",
  "king",
  "brittany",
  "celeste",
  "prada",
  "lilly",
  "magna",
  "belle",
];

export function getProductBySlug(slug) {
  return products.find((p) => p.slug === slug);
}

export function formatPrice(price) {
  return `₹ ${price.toLocaleString("en-IN")}`;
}

export const dealers = [
  {
    id: 1,
    name: "Hayee Furn",
    address: "No 2851, Trichy Road, Thanjavur - 613007",
    city: "Thanjavur",
    pincode: "613007",
    lat: 10.7869,
    lng: 79.1378,
    phone: "+91 96295 19268",
    hoursWeek: "Mon – Sat: 10 AM – 8 PM",
    hoursSun: "Sun: 11 AM – 6 PM",
  },
  {
    id: 2,
    name: "BAARI FURN TRENDZ",
    address: "No 6, Mastha Enclave, Vallam, Thanjavur - 613403",
    city: "Thanjavur",
    pincode: "613403",
    lat: 10.7612,
    lng: 79.1165,
    phone: "+91 96295 19268",
    hoursWeek: "Mon – Sat: 10 AM – 8 PM",
    hoursSun: "Sun: 11 AM – 6 PM",
  },
  {
    id: 3,
    name: "The Maark Trendz",
    address: "390-3A, New Sidhapudur, Coimbatore - 641044",
    city: "Coimbatore",
    pincode: "641044",
    lat: 11.0168,
    lng: 76.9558,
    phone: "+91 96295 19268",
    hoursWeek: "Mon – Sat: 10 AM – 8 PM",
    hoursSun: "Sun: 11 AM – 6 PM",
  },
  {
    id: 4,
    name: "The Maark Trendz",
    address: "Door no 2 & 3, Perundurai Road, Palayapalayam, Erode - 638011",
    city: "Erode",
    pincode: "638011",
    lat: 11.341,
    lng: 77.7172,
    phone: "+91 96295 19268",
    hoursWeek: "Mon – Sat: 10 AM – 8 PM",
    hoursSun: "Sun: 11 AM – 6 PM",
  },
  {
    id: 5,
    name: "Metro Furniture (DMP)",
    address: "Salem Main Road, Lakkiyampatti, Dharmapuri - 636705",
    city: "Dharmapuri",
    pincode: "636705",
    lat: 12.1211,
    lng: 78.1582,
    phone: "+91 96295 19268",
    hoursWeek: "Mon – Sat: 10 AM – 8 PM",
    hoursSun: "Sun: 11 AM – 6 PM",
  },
  {
    id: 6,
    name: "Maharaja Furniture",
    address: "63, Gandhi Road, Kanchipuram - 631501",
    city: "Kanchipuram",
    pincode: "631501",
    lat: 12.8342,
    lng: 79.7036,
    phone: "+91 96295 19268",
    hoursWeek: "Mon – Sat: 10 AM – 8 PM",
    hoursSun: "Sun: 11 AM – 6 PM",
  },
  {
    id: 7,
    name: "HAMEEM MARKETTING",
    address: "No 116-41, Nelson Manickam Road, Aminjikarai, Chennai - 600029",
    city: "Chennai",
    pincode: "600029",
    lat: 13.0827,
    lng: 80.2209,
    phone: "+91 96295 19268",
    hoursWeek: "Mon – Sat: 10 AM – 8 PM",
    hoursSun: "Sun: 11 AM – 6 PM",
  },
  {
    id: 8,
    name: "D FURN",
    address: "48/419, T H Road, Ganga Kaveri Kalyana Mandapam, Thiruvottiyur - 600019",
    city: "Chennai",
    pincode: "600019",
    lat: 13.1582,
    lng: 80.3014,
    phone: "+91 96295 19268",
    hoursWeek: "Mon – Sat: 10 AM – 8 PM",
    hoursSun: "Sun: 11 AM – 6 PM",
  },
];

/** Cities shown on Find a Dealer (reference grid). */
export const findDealerFeaturedCities = [
  "Dharmapuri",
  "Salem",
  "Hosur",
  "Krishnagiri",
  "Bengaluru",
  "Chennai",
].map((name) => ({
  name,
  dealers: dealers.filter((d) => d.city === name).length,
}));

export const popularCities = Object.entries(
  dealers.reduce((acc, dealer) => {
    acc[dealer.city] = (acc[dealer.city] || 0) + 1;
    return acc;
  }, {})
).map(([name, count]) => ({ name, dealers: count }));

export const furnitureCategories = [
  {
    name: "Beds",
    tagline: "Foundation for better sleep",
    description: "Premium bed frames designed to complement Avalon mattresses.",
  },
  {
    name: "Sofas",
    tagline: "Living room luxury",
    description: "Comfortable seating crafted with the same attention to quality.",
  },
  {
    name: "Chairs",
    tagline: "Everyday elegance",
    description: "Stylish chairs for dining, lounge, and workspace.",
  },
  {
    name: "Tables",
    tagline: "Functional beauty",
    description: "Side tables, coffee tables, and dining sets for complete homes.",
  },
];
